
import {Location} from '@interfaces/location';

export const LOCATIONS: Location[] = [
  {
    dep: 'AMAZONAS',
    cities:[
      'El Encanto',
      'La Chorrera',
      'La Pedrera',
      'La Victoria',
      'Leticia',
      'Miriti - Paraná',
      'Puerto Alegria',
      'Puerto Arica',
      'Puerto Nariño',
      'Puerto Santander',
      'Tarapacá' 	
    ]
  },
{
    dep: 'ANTIOQUIA',
    cities:[
      'Cáceres',
      'Caucasia',
      'El Bagre',
      'Nechí',
      'Tarazá',
      'Zaragoza',
      'Caracolí',
      'Maceo',
      'Puerto Berrio',
      'Puerto Nare',
      'Puerto Triunfo',
      'Yondó',
      'Amalfi',
      'Anorí',
      'Cisneros',
      'Remedios',
      'San Roque',
      'Santo Domingo',
      'Segovia',
      'Vegachí',
      'Yalí',
      'Yolombó',
      'Angostura',
      'Belmira',
      'Briceño',
      'Campamento',
      'Carolina',
      'Don Matias',
      'Entrerrios',
      'Gómez Plata',
      'Guadalupe',
      'Ituango',
      'San Andrés',
      'San José De La Montaña',
      'San Pedro',
      'Santa Rosa De Osos',
      'Toledo',
      'Valdivia',
      'Yarumal',
      'Abriaquí',
      'Anza',
      'Armenia',
      'Buriticá',
      'Cañasgordas',
      'Dabeiba',
      'Ebéjico',
      'Frontino',
      'Giraldo',
      'Heliconia',
      'Liborina',
      'Olaya',
      'Peque',
      'Sabanalarga',
      'San Jerónimo',
      'Santafé De Antioquia',
      'Sopetran',
      'Uramita',
      'Abejorral',
      'Alejandría',
      'Argelia',
      'Carmen De Viboral',
      'Cocorná',
      'Concepción',
      'Granada',
      'Guarne',
      'Guatape',
      'La Ceja',
      'La Unión',
      'Marinilla',
      'Nariño',
      'Peñol',
      'Retiro',
      'Rionegro',
      'San Carlos',
      'San Francisco',
      'San Luis',
      'San Rafael',
      'San Vicente',
      'Santuario',
      'Sonson',
      'Amaga',
      'Andes',
      'Angelopolis',
      'Betania',
      'Betulia',
      'Caicedo',
      'Caramanta',
      'Ciudad Bolívar',
      'Concordia',
      'Fredonia',
      'Hispania',
      'Jardín',
      'Jericó',
      'La Pintada',
      'Montebello',
      'Pueblorrico',
      'Salgar',
      'Santa Barbara',
      'Támesis',
      'Tarso',
      'Titiribí',
      'Urrao',
      'Valparaiso',
      'Venecia',
      'Apartadó',
      'Arboletes',
      'Carepa',
      'Chigorodó',
      'Murindó',
      'Mutata',
      'Necoclí',
      'San Juan De Uraba',
      'San Pedro De Uraba',
      'Turbo',
      'Vigía Del Fuerte',
      'Barbosa',
      'Bello',
      'Caldas',
      'Copacabana',
      'Envigado',
      'Girardota',
      'Itagui',
      'La Estrella',
      'Medellín',
      'Sabaneta'
    ]
  },
  {
    dep: 'ARAUCA',
    cities:[	
      'Arauca',
      'Arauquita',
      'Cravo Norte',
      'Fortul',
      'Puerto Rondón',
      'Saravena',
      'Tame'
    ]
  },
  {
    dep: 'ARCHIPIELAGO DE SAN ANDRES',
    cities:[	
      'Providencia Y Santa Catalina',
      'San Andres'
    ]
  },
  {
    dep: 'ATLÁNTICO',
    cities:[	
      'Barranquilla',
      'Galapa',
      'Malambo',
      'Puerto Colombia',
      'Soledad',
      'Campo De La Cruz',
      'Candelaria',
      'Luruaco',
      'Manati',
      'Repelon',
      'Santa Lucia',
      'Suan',
      'Baranoa',
      'Palmar De Varela',
      'Polonuevo',
      'Ponedera',
      'Sabanagrande',
      'Sabanalarga',
      'Juan De Acosta',
      'Santo Tomas',
      'Piojó',
      'Tubara',
      'Usiacuri'
    ]
  }
  
  
];