
import {Location} from '@interfaces/location';

export const LOCATIONS: Location[] = [
  {
    dep: 'AMAZONAS',
    cities:[
      'El Encanto',
      'La Chorrera',
      'La Pedrera',
      'La Victoria',
      'Leticia',
      'Miriti - Paraná',
      'Puerto Alegria',
      'Puerto Arica',
      'Puerto Nariño',
      'Puerto Santander',
      'Tarapacá' 	
    ]
  },
{
    dep: 'ANTIOQUIA',
    cities:[
      'Cáceres',
      'Caucasia',
      'El Bagre',
      'Nechí',
      'Tarazá',
      'Zaragoza',
      'Caracolí',
      'Maceo',
      'Puerto Berrio',
      'Puerto Nare',
      'Puerto Triunfo',
      'Yondó',
      'Amalfi',
      'Anorí',
      'Cisneros',
      'Remedios',
      'San Roque',
      'Santo Domingo',
      'Segovia',
      'Vegachí',
      'Yalí',
      'Yolombó',
      'Angostura',
      'Belmira',
      'Briceño',
      'Campamento',
      'Carolina',
      'Don Matias',
      'Entrerrios',
      'Gómez Plata',
      'Guadalupe',
      'Ituango',
      'San Andrés',
      'San José De La Montaña',
      'San Pedro',
      'Santa Rosa De Osos',
      'Toledo',
      'Valdivia',
      'Yarumal',
      'Abriaquí',
      'Anza',
      'Armenia',
      'Buriticá',
      'Cañasgordas',
      'Dabeiba',
      'Ebéjico',
      'Frontino',
      'Giraldo',
      'Heliconia',
      'Liborina',
      'Olaya',
      'Peque',
      'Sabanalarga',
      'San Jerónimo',
      'Santafé De Antioquia',
      'Sopetran',
      'Uramita',
      'Abejorral',
      'Alejandría',
      'Argelia',
      'Carmen De Viboral',
      'Cocorná',
      'Concepción',
      'Granada',
      'Guarne',
      'Guatape',
      'La Ceja',
      'La Unión',
      'Marinilla',
      'Nariño',
      'Peñol',
      'Retiro',
      'Rionegro',
      'San Carlos',
      'San Francisco',
      'San Luis',
      'San Rafael',
      'San Vicente',
      'Santuario',
      'Sonson',
      'Amaga',
      'Andes',
      'Angelopolis',
      'Betania',
      'Betulia',
      'Caicedo',
      'Caramanta',
      'Ciudad Bolívar',
      'Concordia',
      'Fredonia',
      'Hispania',
      'Jardín',
      'Jericó',
      'La Pintada',
      'Montebello',
      'Pueblorrico',
      'Salgar',
      'Santa Barbara',
      'Támesis',
      'Tarso',
      'Titiribí',
      'Urrao',
      'Valparaiso',
      'Venecia',
      'Apartadó',
      'Arboletes',
      'Carepa',
      'Chigorodó',
      'Murindó',
      'Mutata',
      'Necoclí',
      'San Juan De Uraba',
      'San Pedro De Uraba',
      'Turbo',
      'Vigía Del Fuerte',
      'Barbosa',
      'Bello',
      'Caldas',
      'Copacabana',
      'Envigado',
      'Girardota',
      'Itagui',
      'La Estrella',
      'Medellín',
      'Sabaneta'
    ]
  },
  {
    dep: 'ARAUCA',
    cities:[	
      'Arauca',
      'Arauquita',
      'Cravo Norte',
      'Fortul',
      'Puerto Rondón',
      'Saravena',
      'Tame'
    ]
  },
  {
    dep: 'ARCHIPIELAGO DE SAN ANDRES',
    cities:[	
      'Providencia Y Santa Catalina',
      'San Andres'
    ]
  },
  {
    dep: 'ATLÁNTICO',
    cities:[	
      'Barranquilla',
      'Galapa',
      'Malambo',
      'Puerto Colombia',
      'Soledad',
      'Campo De La Cruz',
      'Candelaria',
      'Luruaco',
      'Manati',
      'Repelon',
      'Santa Lucia',
      'Suan',
      'Baranoa',
      'Palmar De Varela',
      'Polonuevo',
      'Ponedera',
      'Sabanagrande',
      'Sabanalarga',
      'Juan De Acosta',
      'Santo Tomas',
      'Piojó',
      'Tubara',
      'Usiacuri'
    ]
  },
  {
    dep: 'Bogota D.C',
    cities:[
      'Bogota D.C'	
    ]
  },
  {
    dep: 'BOLIVAR',
    cities:[
      'Cicuco',
      'Hatillo De Loba',
      'Margarita',
      'Mompós',
      'San Fernando',
      'Talaigua Nuevo',
      'Arjona',
      'Arroyohondo',
      'Calamar',
      'Cartagena',
      'Mahates',
      'San Cristobal',
      'San Estanislao',
      'Santa Catalina',
      'Santa Rosa De Lima',
      'Soplaviento',
      'Turbaco',
      'Turbana',
      'Villanueva',
      'Altos Del Rosario',
      'Barranco De Loba',
      'Santo Tomas',
      'El Peñon',
      'Regidor',
      'Río Viejo',
      'San Martin De Loba ',
      'Arenal',
      'Cantagallo',
      'Morales',
      'San Pablo',
      'Santa Rosa Del Sur',
      'Achí',
      'Magangué',
      'Montecristo',
      'San Jacinto Del Cauca',
      'Tiquisio',
      'Carmen De Bolívar',
      'Córdoba',
      'El Guamo',
      'María La Baja',
      'San Jacinto',
      'San Juan Nepomuceno',
      'Zambrano'		
    ]
  },
  {
    dep: 'BOYACÁ',
    cities:[
      'Chíquiza',
      'Chivatá',
      'Cómbita',
      'Cucaita',
      'Motavita',
      'Oicatá',
      'Samacá',
      'Siachoque',
      'Sora',
      'Soracá',
      'Sotaquirá',
      'Toca',
      'Tunja',
      'Tuta',
      'Ventaquemada',
      'Chiscas',
      'Cubará',
      'El Cocuy',
      'El Espino',
      'Guacamayas',
      'Güicán',
      'Panqueba',
      'Labranzagrande',
      'Pajarito',
      'Paya',
      'Pisba',
      'Berbeo',
      'Campohermoso',
      'Miraflores',
      'Páez',
      'San Eduardo',
      'Zetaquira',
      'Boyacá',
      'Ciénega',
      'Jenesano',
      'Nuevo Colón',
      'Ramiriquí',
      'Rondón',
      'Tibaná',
      'Turmequé',
      'Umbita',
      'Viracachá',
      'Chinavita',
      'Garagoa',
      'Macanal',
      'Pachavita',
      'San Luis De Gaceno',
      'Santa María',
      'Boavita',
      'Covarachía',
      'La Uvita',
      'San Mateo',
      'Sativanorte',
      'Sativasur',
      'Soatá',
      'Susacón',
      'Tipacoque',
      'Briceño',
      'Buenavista',
      'Caldas',
      'Chiquinquirá',
      'Coper',
      'La Victoria',
      'Maripí',
      'Muzo',
      'Otanche',
      'Pauna',
      'Puerto Boyaca',
      'Quípama',
      'Saboyá',
      'San Miguel De Sema',
      'San Pablo Borbur',
      'Tununguá',
      'Almeida',
      'Chivor',
      'Guateque',
      'Guayatá',
      'La Capilla',
      'Somondoco',
      'Sutatenza',
      'Arcabuco',
      'Chitaraque',
      'Gachantivá',
      'Moniquirá',
      'Ráquira',
      'Sáchica',
      'San José De Pare',
      'Santa Sofía',
      'Sutamarchán',	
      'Tinjacá',
      'Togüí',
      'Villa De Leyva',
      'Aquitania',
      'Cuítiva',	
      'Firavitoba',
      'Gameza',
      'Iza',
      'Mongua',
      'Monguí',
      'Nobsa',
      'Pesca',
      'Sogamoso',
      'Tibasosa',
      'Tópaga',
      'Tota',
      'Belén',
      'Busbanzá',
      'Cerinza',
      'Corrales',
      'Duitama',
      'Floresta',
      'Paipa',
      'San Rosa Viterbo',
      'Tutazá',
      'Betéitiva',
      'Chita',
      'Jericó',
      'Paz De Río',
      'Socha',
      'Socotá',
      'Tasco'
      
    ]
  },
  {
    dep: 'CALDAS',
    cities:[
      'La Merced',
      'Marmato',
      'Riosucio',
      'Supía',
      'Manzanares',
      'Marquetalia',
      'Marulanda',
      'Pensilvania',
      'Belalcázar',
      'Risaralda',
      'San José',
      'Viterbo',
      'Chinchina',
      'Manizales',
      'Neira',
      'Palestina',
      'Villamaria',
      'Aguadas',
      'Aranzazu',
      'Pácora',
      'Salamina',
      'La Dorada',
      'Norcasia',
      'Samaná',
      'Victoria'
    ]
  },
  {
    dep: 'CAQUETA',
    cities:[
      'Albania',
      'Belén De Los Andaquies',
      'Cartagena Del Chairá',
      'Currillo',
      'El Doncello',
      'El Paujil',
      'Florencia',
      'La Montañita',
      'Milan',
      'Morelia',
      'El Paujil',
      'Florencia',
      'La Montañita',
      'Puerto Rico',
      'San Jose Del Fragua',
      'San Vicente Del Caguán',
      'Solano',
      'Solita',
      'Valparaiso'
    ]
  },
  {
    dep: 'CASANARE',
    cities:[
      'Aguazul',
      'Chameza',
      'Hato Corozal',
      'La Salina',
      'Maní',
      'Monterrey',
      'Nunchía',
      'Orocué',
      'Paz De Ariporo',
      'Pore',
      'Recetor',
      'Sabanalarga',
      'Sácama',
      'San Luis De Palenque',
      'Támara',
      'Tauramena',
      'Trinidad',
      'Villanueva',
      'Yopal'
    ]
  },
  {
    dep: 'CAUCA',
    cities:[
        'Cajibío',
        'El Tambo',
        'La Sierra',
        'Morales',
        'Piendamo',
        'Popayán',
        'Rosas',
        'Sotara',
        'Timbio',
        'Buenos Aires',
        'Caloto',
        'Corinto',
        'Miranda',
        'Padilla',
        'Puerto Tejada',
        'Santander De Quilichao',
        'Suarez',
        'Villa Rica',
        'Guapi',
        'Lopez',
        'Timbiqui',
        'Caldono',
        'Inzá',
        'Jambalo',
        'Paez',
        'Purace',
        'Silvia',
        'Toribio',
        'Totoro',
        'Almaguer',
        'Argelia',
        'Balboa',
        'Bolívar',
        'Florencia',
        'La Vega',
        'Mercaderes',
        'Patia',
        'Piamonte',
        'San Sebastian',
        'Santa Rosa',
        'Sucre'
    ]
  },
  {
    dep: 'CESAR',
    cities:[
      'Becerril',
      'Chimichagua',
      'Chiriguana',
      'Curumaní',
      'La Jagua De Ibirico',
      'Pailitas',
      'Tamalameque',
      'Astrea',
      'Bosconia',
      'El Copey',
      'El Paso',
      'Agustín Codazzi',
      'La Paz',
      'Manaure',
      'Pueblo Bello',
      'San Diego',
      'Valledupar',
      'Aguachica',
      'Gamarra',
      'González',
      'La Gloria',
      'Pelaya',
      'Río De Oro',
      'San Alberto',
      'San Martín'
    ]
  },
  {
    dep: 'CHOCO',
    cities:[
      'Atrato',
      'Bagadó',
      'Bojaya',
      'El Carmen De Atrato',
      'Lloró',
      'Medio Atrato',
      'Quibdó',
      'Rio Quito',
      'Acandí',
      'Belén De Bajira',
      'Carmén Del Darién',
      'Riosucio',
      'Unguía',
      'Bahía Solano',
      'Juradó',
      'Nuquí',
      'Alto Baudó',
      'Bajo Baudó',
      'El Litoral Del San Juan',
      'Medio Baudó',
      'Canton De San Pablo',
      'Certegui',
      'Condoto',
      'Itsmina',
      'Medio San Juan',
      'Nóvita',
      'Río Frío',
      'San José Del Palmar',
      'Sipí',
      'Tadó',
      'Union Panamericana'
    ]
  },
  {
    dep: 'CORDOBA',
    cities:[
        'Tierralta',
        'Valencia',
        'Chimá',
        'Cotorra',
        'Lorica',
        'Momil',
        'Purísima',
        'Montería',
        'Canalete',
        'Los Córdobas',
        'Moñitos',
        'Puerto Escondido',
        'San Antero',
        'San Bernardo Del Viento',
        'Chinú',
        'Sahagún',
        'San Andrés Sotavento',
        'Ayapel',
        'Buenavista',
        'La Apartada',
        'Montelíbano',
        'Planeta Rica',
        'Pueblo Nuevo',
        'Puerto Libertador',
        'Cereté',
        'Ciénaga De Oro',
        'San Carlos',
        'San Pelayo'
    ]
  },
	{
    dep: 'CUNDINAMARCA',
    cities:[
        'Chocontá',
        'Macheta',
        'Manta',
        'Sesquilé',
        'Suesca',
        'Tibirita',
        'Villapinzón',
        'Agua De Dios',
        'Girardot',
        'Guataquí',
        'Jerusalén',
        'Nariño',
        'Nilo',
        'Ricaurte',
        'Tocaima',
        'Caparrapí',
        'Guaduas',
        'Puerto Salgar',
        'Albán',
        'La Peña',
        'La Vega',
        'Nimaima',
        'Nocaima',
        'Quebradanegra',
        'San Francisco',
        'Sasaima',
        'Supatá',
        'Útica',
        'Vergara',
        'Villeta',
        'Gachala',
        'Gacheta',
        'Gama',
        'Guasca',
        'Guatavita',
        'Junín',
        'La Calera',
        'Ubalá',
        'Beltrán',
        'Bituima',
        'Chaguaní',
        'Guayabal De Siquima',
        'Puli',
        'San Juan De Río Seco',
        'Vianí',
        'Medina',
        'Paratebueno',
        'Caqueza',
        'Chipaque',
        'Choachí',
        'Fomeque',
        'Fosca',
        'Guayabetal',
        'Gutiérrez',
        'Quetame',
        'Ubaque',
        'Une',
        'El Peñón',
        'La Palma',
        'Pacho',
        'Paime',
        'San Cayetano',
        'Topaipi',
        'Villagomez',
        'Yacopí',
        'Cajicá',
        'Chía',
        'Cogua',
        'Gachancipá',
        'Nemocon',
        'Sopó',
        'Tabio',
        'Tocancipá',
        'Zipaquirá',
        'Bojacá',
        'Cota',
        'El Rosal',
        'Facatativá',
        'Funza',
        'Madrid',
        'Mosquera',
        'Subachoque',
        'Tenjo',
        'Zipacon',
        'Sibaté',
        'Soacha',
        'Arbeláez',
        'Cabrera',
        'Fusagasugá',
        'Granada',
        'Pandi',
        'Pasca',
        'San Bernardo',
        'Silvania',
        'Tibacuy',
        'Venecia',
        'Anapoima',
        'Anolaima',
        'Apulo',
        'Cachipay',
        'El Colegio',
        'La Mesa',
        'Quipile',
        'San Antonio De Tequendama',
        'Tena',
        'Viotá',
        'Carmen De Carupa',
        'Cucunubá',
        'Fúquene',
        'Guachetá',
        'Lenguazaque',
        'Simijaca',
        'Susa',
        'Sutatausa',
        'Tausa',
        'Ubate'
    ]
  },
  {
    dep: 'GUAINIA',
    cities:[
        'Barranco Mina',
        'Cacahual',
        'Inírida',
        'La Guadalupe',
        'Mapiripan',
        'Morichal',
        'Pana Pana',
        'Puerto Colombia',
        'San Felipe'
    ]
  },
  {
    dep: 'GUAVIARE',
    cities:[
        'Calamar',
        'El Retorno',
        'Miraflores',
        'San José Del Guaviare'
    ]
  },
  {
    dep: 'HUILA',
    cities:[
        'Agrado',
        'Altamira',
        'Garzón',
        'Gigante',
        'Guadalupe',
        'Pital',
        'Suaza',
        'Tarqui',
        'Aipe',
        'Algeciras',
        'Baraya',
        'Campoalegre',
        'Colombia',
        'Hobo',
        'Iquira',
        'Neiva',
        'Palermo',
        'Rivera',
        'Santa María',
        'Tello',
        'Teruel',
        'Villavieja',
        'Yaguará',
        'La Argentina',
        'La Plata',
        'Nátaga',
        'Paicol',
        'Tesalia',
        'Acevedo',
        'Elías',
        'Isnos',
        'Oporapa',
        'Palestina',
        'Pitalito',
        'Saladoblanco',
        'San Agustín',
        'Timaná'
    ]
  },
  {
    dep: 'LA GUAJIRA',
    cities:[
        'Albania',
        'Dibulla',
        'Maicao',
        'Manaure',
        'Riohacha',
        'Uribia',
        'Barrancas',
        'Distraccion',
        'El Molino',
        'Fonseca',
        'Hatonuevo',
        'La Jagua Del Pilar',
        'San Juan Del Cesar',
        'Urumita',
        'Villanueva'
    ]
  },
  {
    dep: 'MAGDALENA',
    cities:[
        'Ariguaní',
        'Chibolo',
        'Nueva Granada',
        'Plato',
        'Sabanas De San Angel',
        'Tenerife',
        'Algarrobo',
        'Aracataca',
        'Ciénaga',
        'El Reten',
        'Fundacion',
        'Pueblo Viejo',
        'Zona Bananera',
        'Cerro San Antonio',
        'Concordia',
        'El Piñon',
        'Pedraza',
        'Pivijay',
        'Remolino',
        'Salamina',
        'Sitionuevo',
        'Zapayan',
        'Santa Marta',
        'El Banco',
        'Guamal',
        'Pijiño Del Carmen',
        'San Sebastian De Buenavista',
        'San Zenon',
        'Santa Ana',
        'Santa Barbara De Pinto'
    ]
  },
  {
    dep: 'META',
    cities:[
        'El Castillo',
        'El Dorado',
        'Fuente De Oro',
        'Granada',
        'La Macarena',
        'La Uribe',
        'Lejanías',
        'Mapiripan',
        'Mesetas',
        'Puerto Concordia',
        'Puerto Lleras',
        'Puerto Rico',
        'San Juan De Arama',
        'Vista Hermosa',
        'Villavicencio',
        'Acacias',
        'Barranca De Upia',
        'Castilla La Nueva',
        'Cumaral',
        'El Calvario',
        'Guamal',
        'Restrepo',
        'San Carlos Guaroa',
        'San Juanito',
        'San Luis De Cubarral',
        'San Martín',
        'Cabuyaro',
        'Puerto Gaitán',
        'Puerto Lopez'
    ]
  },
  {
    dep: 'NARIÑO',
    cities:[
        'Chachagui',
        'Consaca',
        'El Peñol',
        'El Tambo',
        'La Florida',
        'Nariño',
        'Pasto',
        'Sandoná',
        'Tangua',
        'Yacuanquer',
        'Ancuya',
        'Guaitarilla',
        'La Llanada',
        'Linares',
        'Los Andes',
        'Mallama',
        'Ospina',
        'Providencia',
        'Ricaurte',
        'Samaniego',
        'Santa Cruz',
        'Sapuyes',
        'Tuquerres',
        'Barbacoas',
        'El Charco',
        'Francisco Pizarro',
        'La Tola',
        'Magui',
        'Mosquera',
        'Olaya Herrera',
        'Roberto Payan',
        'Santa Barbara',
        'Tumaco',
        'Alban',
        'Arboleda',
        'Belen',
        'Buesaco',
        'Colon',
        'Cumbitara',
        'El Rosario',
        'El Tablon De Gomez',
        'La Cruz',
        'La Union',
        'Leiva',
        'Policarpa',
        'San Bernardo',
        'San Lorenzo',
        'San Pablo',
        'San Pedro De Cartago',
        'Taminango',
        'Aldana',
        'Contadero',
        'Córdoba',
        'Cuaspud',
        'Cumbal',
        'Funes',
        'Guachucal',
        'Gualmatan',
        'Iles',
        'Imues',
        'Ipiales',
        'Potosí',
        'Puerres',
        'Pupiales'
    ]
  },
  {
    dep: 'NORTE DE SANTANDER',
    cities:[
        'Arboledas',
        'Cucutilla',
        'Gramalote',
        'Lourdes',
        'Salazar',
        'Santiago',
        'Villa Caro',
        'Bucarasica',
        'El Tarra',
        'Sardinata',
        'Tibú',
        'Abrego',
        'Cachirá',
        'Convención',
        'El Carmen',
        'Hacarí',
        'La Esperanza',
        'La Playa',
        'Ocaña',
        'San Calixto',
        'Teorama',
        'Cúcuta',
        'El Zulia',
        'Los Patios',
        'Puerto Santander',
        'San Cayetano',
        'Villa Del Rosario',
        'Cácota',
        'Chitagá',
        'Mutiscua',
        'Pamplona',
        'Pamplonita',
        'Silos',
        'Bochalema',
        'Chinácota',
        'Durania',
        'Herrán',
        'Labateca',
        'Ragonvalia',
        'Toledo'
    ]
  },
  {
    dep: 'PUTUMAYO',
    cities:[
        'Colón',
        'Mocoa',
        'Orito',
        'Puerto Asis',
        'Puerto Caicedo',
        'Puerto Guzman',
        'Puerto Leguizamo',
        'San Francisco',
        'San Miguel',
        'Santiago',
        'Sibundoy',
        'Valle Del Guamuez',
        'Villa Garzon'
    ]
  }

  
		
];